Major refactor of `recover` parser

diff --git a/scripts/wirescale-autoremove b/scripts/wirescale-autoremove
--- a/scripts/wirescale-autoremove
+++ b/scripts/wirescale-autoremove
@@ -21,8 +21,6 @@ get_sleep_times() {
 }
 
 check_interface_and_file() {
-  interface=$1
-  flag_file="/run/wirescale/control/$interface-stop"
   if { ip link show "$interface"; } > /dev/null 2>&1 && [ ! -f "$flag_file" ]; then
     return 0
   else
@@ -43,36 +41,26 @@ latest_handshake_less_than() {
 }
 
 ping_periodic() {
-  interface=$1
-  ip=$2
-
   start_time=$(date +%s)
-
-  while check_interface_and_file "$interface" && [ $(($(date +%s) - start_time)) -lt 4500 ]; do
-    ping -q -I "$interface" -c 1 -W 0.05 "$ip" > /dev/null 2>&1
+  while check_interface_and_file && [ $(($(date +%s) - start_time)) -lt 4500 ]; do
+    ping -q -I "$interface" -c 1 -W 0.05 "$wg_ip" > /dev/null 2>&1
     sleep 5
   done
 }
 
 assure_connection() {
-  interface=$1
-  remote_pubkey=$2
-  file=$3
+  file=$1
 
   listen_port=$(wg show "$interface" listen-port)
   endpoint=$(wg show "$interface" endpoints | awk -v pubkey="$remote_pubkey" '$1 == pubkey {print $2}')
-  [ -z $endpoint ] && echo "Interface $interface has no peer with public key $remote_pubkey" && return 0
+  [ -z "$endpoint" ] && echo "Interface $interface has no peer with public key $remote_pubkey" && return 0
   wg set "$interface" listen-port 0
   { cat "$file" | socat UDP:"$endpoint",sourceport="$listen_port" -; } > /dev/null 2>&1
   wg set "$interface" listen-port "$listen_port"
 }
 
 assure_keepalive() {
-  interface=$1
-  remote_pubkey=$2
-  is_remote=$3
-  start_time=$4
-  lockfile="/run/wirescale/control/locker-$interface"
+  start_time=$1
 
   if [ "$is_remote" -eq 1 ]; then
     start_time=$(((start_time + 30) % 60))
@@ -81,13 +69,13 @@ assure_keepalive() {
   dummy_file="/tmp/dummy-$interface.zip"
   counter=0
   total=60
-  while check_interface_and_file "$interface" && [ "$counter" -lt "$total" ]; do
+  while check_interface_and_file && [ "$counter" -lt "$total" ]; do
     dd if=/dev/urandom of="$dummy_file" bs=2K count=$((counter + 1)) > /dev/null 2>&1
     sleep "$(calculate_sleep_time "$start_time")"
     echo "Sending special package to assure connection, $((counter + 1))/$total"
     (
       flock 9
-      assure_connection "$interface" "$remote_pubkey" "$dummy_file"
+      assure_connection "$dummy_file"
     ) 9> "$lockfile"
     rm -rf "$dummy_file"
     counter=$((counter + 1))
@@ -96,24 +84,17 @@ assure_keepalive() {
 }
 
 change_keepalive() {
-  interface=$1
-  remote_pubkey=$2
-  seconds=$3
+  seconds=$1
   wg set "$interface" peer "$remote_pubkey" persistent-keepalive "$seconds"
 }
 
 ping_keepalive() {
-  interface=$1
-  remote_pubkey=$2
-  wg_ip=$3
-  is_remote=$4
-  start_time=$5
-
+  start_time=$1
   start_time_func=$(date +%s)
 
-  ping_periodic "$interface" "$wg_ip" &
+  ping_periodic &
 
-  while check_interface_and_file "$interface" && [ $(($(date +%s) - start_time_func)) -lt 4500 ]; do
+  while check_interface_and_file && [ $(($(date +%s) - start_time_func)) -lt 4500 ]; do
     if [ "$is_remote" -eq 1 ]; then
       sleep_times=$(get_sleep_times "$start_time")
       sleep "$(calculate_sleep_time "$sleep_times")"
@@ -130,16 +111,10 @@ ping_keepalive() {
 }
 
 recover() {
-  interface=$1
-  ts_ip=$2
-  remote_interface=$3
-  remote_port=$4
-  local_port=$(wg show "$interface" listen-port)
-
   wait_time=30
   while { ip link show "$interface"; } > /dev/null 2>&1; do
     echo "Trying to force a new endpoint..."
-    wirescale recover --peer "$ts_ip" --interface "$interface" --port "$local_port" --remote-interface "$remote_interface" --remote-port "$remote_port"
+    wirescale recover "$interface"
     status=$?
     if [ "$status" -eq 0 ]; then
       echo "Success! Connection recovered. Restarting this unit..."
@@ -148,16 +123,16 @@ recover() {
       echo "Error: It was impossible to recover the connection"
       return 1
     elif [ "$status" -eq 2 ]; then
-      echo "Error: The other peer is unreachable for the moment. Will try again in $wait_time seconds..."
+      echo "Error: The other peer is currently unreachable. Will try again in $wait_time seconds..."
+    elif [ "$status" -eq 3 ]; then
+      echo "Error: The latest handshake has been updated, so connection is not dead. Restarting this unit..."
+      systemctl restart autoremove-"$interface".service
     fi
     sleep "$wait_time"
   done
 }
 
 remove_interface() {
-  interface=$1
-  lockfile="/run/wirescale/control/locker-$interface"
-
   echo "Removing interface $interface"
   (
     flock 9
@@ -175,30 +150,32 @@ autoremove() {
   wg_ip=$4
   is_remote=$5
   start_time=$6
-  remote_interface=$7
-  remote_port=$8
-  local_port=$(wg show "$interface" listen-port)
+  local_port=$7
+  remote_interface=$8
+  remote_port=$9
   lockfile="/run/wirescale/control/locker-$interface"
+  flag_file="/run/wirescale/control/$interface-stop"
+  export interface ts_ip remote_pubkey wg_ip is_remote local_port remove_interface remote_port lockfile flag_file
 
   start_time_func=$(date +%s)
   last_received=0
 
-  rm -rf "/run/wirescale/control/$interface-stop"
+  rm -rf "$flag_file"
 
-  ping_keepalive "$interface" "$remote_pubkey" "$wg_ip" "$is_remote" "$start_time" &
+  ping_keepalive "$start_time" &
 
-  assure_keepalive "$interface" "$remote_pubkey" "$is_remote" "$start_time" &
+  assure_keepalive "$start_time" &
 
   sleep "$(calculate_sleep_time "$start_time")" # A pause to synchronize both peers and let them have sufficient time for proper setup
 
   while { ip link show "$interface"; } > /dev/null 2>&1; do
     if [ $(($(date +%s) - start_time_func)) -ge 4500 ]; then
       echo "Terminating the primary autoremove function, as over 75 minutes have elapsed since the script began"
-      autoremove_three_min "$interface"
+      autoremove_three_min
     fi
-    if ! check_interface_and_file "$interface"; then
-      echo "Terminating the primary autoremove function, as flag file '/run/wirescale/control/$interface-stop' exists"
-      autoremove_three_min "$interface"
+    if ! check_interface_and_file; then
+      echo "Terminating the primary autoremove function, as flag file '$flag_file' exists"
+      autoremove_three_min
     fi
     received=$(wg show "$interface" transfer | awk -v pubkey="$remote_pubkey" '$1 == pubkey {print $2}')
     if [ "$received" -gt "$last_received" ]; then
@@ -208,30 +185,29 @@ autoremove() {
       if latest_handshake_less_than "$interface" "$remote_pubkey" 10; then
         echo "...but the latest handshake was less than ten seconds ago, so won't do anything for now"
       else
-        touch "/run/wirescale/control/$interface-stop"
+        touch "$flag_file"
         break
       fi
     fi
     sleep 40
   done
 
-  recover "$interface" "$ts_ip" "$remote_interface" "$remote_port"
-  remove_interface "$interface"
+  recover
+  remove_interface
 }
 
 autoremove_three_min() {
-  interface=$1
-  lockfile="/run/wirescale/control/locker-$interface"
-
   echo "Launching autoremove function to check for handshakes older than 3 minutes"
   while { ip link show "$interface"; } > /dev/null 2>&1; do
     if ! latest_handshake_less_than "$interface" "$remote_pubkey" 180; then
       echo "Connection broken. More than three minutes without handshake."
-      recover "$interface" "$ts_ip" "$remote_interface" "$remote_port"
-      remove_interface "$interface"
+      recover
+      remove_interface
     fi
     sleep 30
   done
+
+  exit 0
 }
 
 # Ensure at least one argument (the function name) was provided
